# Site settings
title: JdeJ
email: me@montalvomiguelo.com
description: Programador en pañales
keywords: web developer, programming, java, javascript, css, html5
author: JdeJ
baseurl: ""
url: "http://jdej.github.io"
twitter_username: JorgedeJuana
github_username:  JdeJ
mail: jorgedjuana@gmail.com
permalink: pretty

# Build settings
markdown: kramdown
